### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by vishaljbhandari** [vishaljbhandari/learn_typescript#1]
[Typescript: The Complete Developer's Guide](https://www.udemy.com/course/typescript-the-complete-developers-guide/)
- [x] How to Get Help
- [x] Join Our Community!
- [x] Course Resources
- [x] Typescript Overview
- [x] Environment Setup
- [x] Important Axios Version Information
- [x] A First App
- [x] Executing Typescript Code
- [x] One Quick Change
- [x] Catching Errors with Typescript
- [x] Catching More Errors!

**Comment by vishaljbhandari** [comment]
**Task -> Typescript Overview**

[Wiki Page -> TypeScript Overview](https://github.com/vishaljbhandari/learn_typescript/wiki/Typescript-Overview)

**Comment by vishaljbhandari** [comment]
**Task -> Environment Setup**

[Wiki Page -> Environment Setup](https://github.com/vishaljbhandari/learn_typescript/wiki/Environment-Setup)

**Comment by vishaljbhandari** [comment]
**Task -> A First App**

**Task -> Executing Typescript Code**

[Wiki Page -> A First App](https://github.com/vishaljbhandari/learn_typescript/wiki/Creating-First-App)
